### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by locklocklock** [light-Life/FOFAbat#1]
使用fofapro.py查询，出现报错:
Traceback (most recent call last):
  File ".\fofapro.py", line 62, in <module>
    res = json.loads((response.content).decode('utf-8'))
  File "D:\python37\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

————————————————————————————————
debug发现对api的请求返回是504，内容为空

————————————————————————————————
环境：Windows + python 3.8.1    
           CentOS7  + python 3.6.8

**Comment by light-Life** [comment]
> 使用fofapro.py查询，出现报错: Traceback (most recent call last): File ".\fofapro.py", line 62, in res = json.loads((response.content).decode('utf-8') ) 文件“D:\python37\lib\json_init __.py_ ”，第 357 行，加载 返回 _default_decoder.decode(s) 文件“D:\python37\lib\json\decoder.py”，第 337 行，在解码中 obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 文件“D:\python37\lib\json\decoder.py”，第 355 行，在 raw_decode 中 引发 JSONDecodeError("期望值", s, err.value) 来自无 json.decoder.JSONDecodeError：期望值：第 1 行第 1 列（字符 0）
> 
> ———————————————————————————————— 调试发现对api的请求返回是504，内容为空
> 
> ———————————————————————————————— 环境：Windows + python 3.8.1 CentOS7 + python 3.6

发现两个问题：
1.数据量过大无法转换格式
2.通过询问fofa内部小哥，某些查询方法如果通过api进行查询会受到过滤，如：title（现在太敏感了，理解即可）
![3CBE1C1F-5774-4BF7-A75D-31318C41E5B4](https://user-images.githubusercontent.com/53685855/157157870-0f8205f1-f43a-4005-85f2-4c3c0feac3a3.png)
暂时解决办法：
只保留功能1，其余功能等有时间再开发
